import { registerSW } from 'virtual:pwa-register';

/**
 * Register the service worker generated by vite-plugin-pwa. Auto-updates in the
 * background; when a new version finishes installing it takes over on next load.
 * No-op in environments without service-worker support.
 */
export function registerServiceWorker(): void {
  registerSW({ immediate: true });
}
